### ISSUE TITLE
Fails to build on OSX

### ISSUE THREAD

**Issue by noahr** [pflarr/dns_parse#8]
Attempted to build on OSX 10.11.6, but was unable to do so. The attached patch fixes the issue, although I don't claim it's the best way (or that the updates are even in the best files); I know just enough C to be a danger to myself and others. 

[dns_parse_osx.patch.gz](https://github.com/pflarr/dns_parse/files/576675/dns_parse_osx.patch.gz)

**Comment by pflarr** [comment]
I tested and incorporated your changes. Thanks.
